/geometric_controller_node:
  ros__parameters:
    mass: 2.0
    use_external_yaw: true
    gains:
      pos:
        x: 10.0
        y: 10.0
        z: 15.0
      vel:
        x: 5.0
        y: 5.0
        z: 10.0
      ki:
        x: 0.0
        y: 0.0
        z: 0.0
      kib:
        x: 0.0
        y: 0.0
        z: 0.0
      rot:
        x: 1.0
        y: 1.0
        z: 0.5
      ang:
        x: 0.13
        y: 0.13
        z: 0.1
    drag:
      kd:
        x: 0.0
        y: 0.0
        z: 0.0
    attctrl_tau: 0.4
    max_pos_int: 1.0
    mas_pos_int_b: 1.0
    max_tilt_angle: 0.6853  # rad
    max_accel: 10.0
    yaw_gain: 0.4 # For the reduced attitude controller
